version: '3.8'

services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: workouts
    volumes:
      - ./backend/workout-service/init/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - backend

  mongo:
    image: mongo:6
    networks:
      - backend

  workout-service:
    build: ./backend/workout-service
    depends_on:
      - postgres
    environment:
      - PORT=3000
      - PGHOST=postgres
      - PGUSER=user
      - PGPASSWORD=password
      - PGDATABASE=workouts
    networks:
      - backend

  nutrition-service:
    build: ./backend/nutrition-service
    depends_on:
      - mongo
    environment:
      - PORT=3000
      - MONGO_URI=mongodb://mongo:27017/nutrition
    networks:
      - backend

  nginx:
    build: ./backend/nginx
    ports:
      - "3000:80"
    depends_on:
      - nutrition-service
      - workout-service
    networks:
      - backend

  auth-service:
    build: ./backend/auth-service
    ports:
      - "3003:3000"
    networks:
      - backend

networks:
  backend:
